ДЗ #1
xhrobj/Otus.Golang_Developer.Homeworks pull request #1
Opened 2023-12-12 19:29 UTC by xhrobj

## Домашнее задание №1 «Hello, OTUS!»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Используется `stringutil` - 4 балла
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-12-13 02:14 UTC, dshemin requested changes

2023-12-13 02:14 UTC, dshemin commented on hw01_hello_otus/go.mod
> +module github.com/xhrobj/Otus.Golang.Developer.Homeworks/tree/master/hw01_hello_otus
Критично:

Не совсем верно, `/tree/master` тут лишнее.

2023-12-13 19:25 UTC, xhrobj commented on hw01_hello_otus/go.mod
> +module github.com/xhrobj/Otus.Golang.Developer.Homeworks/tree/master/hw01_hello_otus
удалил из идентификатора модуля лишнюю часть пути

2023-12-24 07:09 UTC, dshemin approved these changes

2023-12-24 09:13 UTC, merged